name: nodeseek鸡腿签到

on:
  push:
    branches:
      - shell  # 在 main 分支上进行推送时触发 
  schedule:
    - cron: '00 16 * * *'  # 每天凌晨 12 点执行 
  workflow_dispatch:  # 添加手动触发

jobs:
  run-nodeseek-sign:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: run
        env:
          COOKIE: ${{ secrets.COOKIE }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          THREAD_ID: ${{ secrets.THREAD_ID }}
        run: bash nodeseek_sign.sh
